# Generated by Django 3.0.6 on 2020-06-02 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[[1, 'NEW'], [2, 'IN_PROGRESS'], [3, 'COMPLETED']], default=1)),
                ('label', models.IntegerField(choices=[[1, 'PERSONAL'], [2, 'WORK'], [3, 'SHOPPING'], [4, 'OTHERS']], default=4)),
                ('priority', models.IntegerField(choices=[[1, 'LOW'], [2, 'MEDIUM'], [3, 'HIGH']], default=2)),
                ('archived', models.BooleanField(default=False)),
                ('assigned_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user.UserProfile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_info', to='task.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=200)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
