# Generated by Django 3.0.6 on 2020-06-06 07:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import task.validators


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200602_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='timeline',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, validators=[task.validators.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'completed': {type: 'array'}, 'in_progress': {type: 'array'}, 'new': {type: 'array'}}, 'required': [], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
    ]
