# Generated by Django 3.0.6 on 2020-06-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200606_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='guest_organizations',
            field=models.ManyToManyField(blank=True, related_name='guest_users', to='user.Organization'),
        ),
    ]
